version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo "Build step - no build needed for static site"
artifacts:
  files:
    - '**/*'
  base-directory: . # This is the root directory where your index.html is
